dstp:
  options:
    headless: false
    sloMo: 250
  tasks:
    name: test
    baseUrl: https://example.com
    enabled: true
    commands:
      - command: Goto
        url: 'a'
      - command: SetInput
        selector: b
        value: a
